# Generated by Django 2.1.2 on 2018-11-26 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0005_project_accepted_bid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedMilestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateTimeField(default=None)),
                ('file', models.FileField(blank=True, upload_to='files/')),
                ('is_done', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AcceptedProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.IntegerField()),
                ('deadline', models.DateTimeField()),
                ('file', models.FileField(blank=True, upload_to='files/')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, default=None, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, default=None, max_digits=10, null=True)),
                ('accepted_bid', models.IntegerField(blank=True, default=0)),
                ('is_done', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Category')),
                ('freelancer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(related_name='acceptedprojects', to='project.Tag')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='acceptedmilestone',
            name='acceptedproject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acceptedProject.AcceptedProject'),
        ),
        migrations.AddField(
            model_name='acceptedmilestone',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
