# Generated by Django 2.1.2 on 2018-11-28 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acceptedProject', '0005_auto_20181128_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptedproject',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Category'),
        ),
        migrations.AlterField(
            model_name='acceptedproject',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='acceptedprojects', to='project.Tag'),
        ),
    ]
