# Generated by Django 2.1.2 on 2018-11-28 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acceptedProject', '0007_auto_20181128_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptedproject',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
