# Generated by Django 2.1.2 on 2018-11-28 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acceptedProject', '0008_auto_20181128_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acceptedproject',
            name='category',
        ),
        migrations.RemoveField(
            model_name='acceptedproject',
            name='tags',
        ),
    ]
