# Generated by Django 2.1.2 on 2018-11-29 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceptedProject', '0009_auto_20181128_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelforbackend',
            name='project_id',
            field=models.IntegerField(default=0),
        ),
    ]
