# Generated by Django 2.1.2 on 2018-11-29 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceptedProject', '0010_modelforbackend_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelforbackend',
            name='acceptedproject_id',
            field=models.IntegerField(default=0),
        ),
    ]
