# Generated by Django 2.1.2 on 2018-11-29 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acceptedProject', '0011_modelforbackend_acceptedproject_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelforbackend',
            old_name='acceptedproject_id',
            new_name='accepted_bid',
        ),
    ]
