# Generated by Django 2.1.2 on 2018-11-30 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acceptedProject', '0012_auto_20181129_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelforbackend',
            name='freelancer_id',
        ),
        migrations.RemoveField(
            model_name='modelforbackend',
            name='price',
        ),
        migrations.RemoveField(
            model_name='modelforbackend',
            name='project_id',
        ),
    ]
