# Generated by Django 2.1.2 on 2018-11-30 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_remove_project_accepted_bid'),
        ('acceptedProject', '0013_auto_20181130_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptedproject',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Category'),
        ),
        migrations.AddField(
            model_name='acceptedproject',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='acceptedprojects', to='project.Tag'),
        ),
    ]
