# Generated by Django 2.1.2 on 2018-11-30 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acceptedProject', '0014_auto_20181130_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acceptedproject',
            name='category',
        ),
        migrations.RemoveField(
            model_name='acceptedproject',
            name='tags',
        ),
    ]
