# Generated by Django 2.1.2 on 2018-12-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceptedProject', '0015_auto_20181130_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acceptedmilestone',
            old_name='is_done',
            new_name='is_done_client',
        ),
        migrations.RenameField(
            model_name='acceptedproject',
            old_name='is_done',
            new_name='is_done_client',
        ),
        migrations.AddField(
            model_name='acceptedmilestone',
            name='is_done_freelancer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='acceptedproject',
            name='is_done_freelancer',
            field=models.BooleanField(default=False),
        ),
    ]
