# Generated by Django 2.1.2 on 2018-12-24 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RefinedBy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Selector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='StartEndSelector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('refinedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.RefinedBy')),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField()),
                ('selector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.Selector')),
            ],
        ),
        migrations.CreateModel(
            name='TextAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.Body')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.Target')),
            ],
        ),
        migrations.AddField(
            model_name='selector',
            name='endSelector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endSelector', to='annotation.StartEndSelector'),
        ),
        migrations.AddField(
            model_name='selector',
            name='startSelector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startSelector', to='annotation.StartEndSelector'),
        ),
    ]
