# Generated by Django 2.1.2 on 2018-12-29 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('annotation', '0003_textannotation_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FragmentSelector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ImageAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.Body')),
            ],
        ),
        migrations.CreateModel(
            name='ImageTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField()),
                ('scope', models.TextField()),
                ('selector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.FragmentSelector')),
            ],
        ),
        migrations.AddField(
            model_name='imageannotation',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.ImageTarget'),
        ),
        migrations.AddField(
            model_name='imageannotation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
