# Generated by Django 2.1.2 on 2018-11-08 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_bid_milestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='deadline',
            field=models.DateTimeField(default=None),
        ),
    ]
