# Generated by Django 2.1.2 on 2018-11-30 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_project_accepted_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='accepted_bid',
        ),
    ]
