# Generated by Django 2.1.2 on 2018-10-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20181020_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='John Doe', max_length=255),
        ),
    ]
