# Generated by Django 2.1.2 on 2018-11-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20181026_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(0, 'Freelancer'), (1, 'Client')], default=0),
        ),
    ]
