# Generated by Django 2.1.2 on 2019-01-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_semanticsearch'),
        ('user', '0011_auto_20190101_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='tags',
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='tags',
            field=models.ManyToManyField(related_name='clients', to='project.Tag'),
        ),
        migrations.RemoveField(
            model_name='freelancerprofile',
            name='tags',
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='tags',
            field=models.ManyToManyField(related_name='freelancers', to='project.Tag'),
        ),
    ]
